### ISSUE TITLE
[Info] Generated binding available

### ISSUE THREAD

**Issue by TechMagister** [manastech/crystal-sqlite3#8]
Hello,
I wrote a kind of generator, and, as I generated sqlite3 bindings to test it, I though you may be interested : 
The generated file is here : https://github.com/TechMagister/bindgencr/blob/master/samples/sqlite3/lib_sqlite3.cr
The project : https://github.com/TechMagister/bindgencr/

**Comment by bcardiff** [comment]
Hi @TechMagister , thanks. Are you aware of https://github.com/crystal-lang/crystal_lib ? Might be a better place to compare and improve automated bindings.

From what I see on the bindings you are sending, some pointers are declared as `Type[0]` as in 

```
  struct Sqlite3
    __data : UInt8[0]
  end
```

Even so, thanks! and we could definitely use some of those binding to improve ours upon need. It's far more comfortable to read that than C declarations :-)
